kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "okd-pipeline-demo"
spec:
  source:
    git:
      uri: "https://github.com/juan-sp-si/okd-demo.git"
    sourceSecret: 
      name: github-ssh
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile

